<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 Getting Started | An Introduction to R programming</title>
  <meta name="description" content="Chapter 1 Getting Started | An Introduction to R programming" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 Getting Started | An Introduction to R programming" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 Getting Started | An Introduction to R programming" />
  
  
  

<meta name="author" content="Nicholas Henderson" />


<meta name="date" content="2025-08-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="ifelse.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Getting Started</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> <span style="color:#D96716"><strong>R</strong></span> and <span style="color:#D96716"><strong>RStudio</strong></span></a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#an-extended-example-the-nyc-flights-data"><i class="fa fa-check"></i><b>1.2</b> An Extended Example: the NYC flights data</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="intro.html"><a href="intro.html#installing-r-packages"><i class="fa fa-check"></i><b>1.2.1</b> Installing R packages</a></li>
<li class="chapter" data-level="1.2.2" data-path="intro.html"><a href="intro.html#nyc-flights-data-details"><i class="fa fa-check"></i><b>1.2.2</b> NYC flights data details</a></li>
<li class="chapter" data-level="1.2.3" data-path="intro.html"><a href="intro.html#summarizing-specific-data-variables"><i class="fa fa-check"></i><b>1.2.3</b> Summarizing specific data variables</a></li>
<li class="chapter" data-level="1.2.4" data-path="intro.html"><a href="intro.html#subsetting-data"><i class="fa fa-check"></i><b>1.2.4</b> Subsetting Data</a></li>
<li class="chapter" data-level="1.2.5" data-path="intro.html"><a href="intro.html#plotting-data"><i class="fa fa-check"></i><b>1.2.5</b> Plotting Data</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#using-r-as-a-calculator"><i class="fa fa-check"></i><b>1.3</b> Using R as a calculator</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#variables-in-r"><i class="fa fa-check"></i><b>1.4</b> Variables in R</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="intro.html"><a href="intro.html#rules-for-choosing-variable-names-in-r"><i class="fa fa-check"></i><b>1.4.1</b> Rules for choosing <strong>variable names</strong> in R</a></li>
<li class="chapter" data-level="1.4.2" data-path="intro.html"><a href="intro.html#variable-assignment"><i class="fa fa-check"></i><b>1.4.2</b> Variable Assignment</a></li>
<li class="chapter" data-level="1.4.3" data-path="intro.html"><a href="intro.html#types-of-variables"><i class="fa fa-check"></i><b>1.4.3</b> Types of variables</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#r-operations-with-numbers"><i class="fa fa-check"></i><b>1.5</b> R Operations with numbers</a></li>
<li class="chapter" data-level="1.6" data-path="intro.html"><a href="intro.html#brief-introduction-to-vectors-in-r"><i class="fa fa-check"></i><b>1.6</b> Brief introduction to vectors in R</a></li>
<li class="chapter" data-level="1.7" data-path="intro.html"><a href="intro.html#writing-comments-in-r"><i class="fa fa-check"></i><b>1.7</b> Writing Comments in R</a></li>
<li class="chapter" data-level="1.8" data-path="intro.html"><a href="intro.html#exercises"><i class="fa fa-check"></i><b>1.8</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>I R Programming Fundamentals</b></span></li>
<li class="chapter" data-level="2" data-path="ifelse.html"><a href="ifelse.html"><i class="fa fa-check"></i><b>2</b> Logical Expressions and If-Else Statements in R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="ifelse.html"><a href="ifelse.html#logical-expression-in-r"><i class="fa fa-check"></i><b>2.1</b> Logical Expression in R</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="ifelse.html"><a href="ifelse.html#comparison-operators"><i class="fa fa-check"></i><b>2.1.1</b> Comparison Operators</a></li>
<li class="chapter" data-level="2.1.2" data-path="ifelse.html"><a href="ifelse.html#logical-operators"><i class="fa fa-check"></i><b>2.1.2</b> Logical Operators</a></li>
<li class="chapter" data-level="2.1.3" data-path="ifelse.html"><a href="ifelse.html#precedence-with-logical-operations"><i class="fa fa-check"></i><b>2.1.3</b> Precedence with logical operations</a></li>
<li class="chapter" data-level="2.1.4" data-path="ifelse.html"><a href="ifelse.html#abbreviating-true-and-false-with-t-and-f"><i class="fa fa-check"></i><b>2.1.4</b> Abbreviating TRUE and FALSE with T and F</a></li>
<li class="chapter" data-level="2.1.5" data-path="ifelse.html"><a href="ifelse.html#examples-of-logical-operations-in-r"><i class="fa fa-check"></i><b>2.1.5</b> Examples of logical operations in R</a></li>
<li class="chapter" data-level="2.1.6" data-path="ifelse.html"><a href="ifelse.html#logical-operators-and-vectors"><i class="fa fa-check"></i><b>2.1.6</b> logical operators and vectors</a></li>
<li class="chapter" data-level="2.1.7" data-path="ifelse.html"><a href="ifelse.html#vs.-and-vs."><i class="fa fa-check"></i><b>2.1.7</b> &amp;&amp; vs. &amp; and || vs. |</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="ifelse.html"><a href="ifelse.html#if-and-if-else-statements"><i class="fa fa-check"></i><b>2.2</b> If and If-else statements</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="ifelse.html"><a href="ifelse.html#if-statements"><i class="fa fa-check"></i><b>2.2.1</b> if statements</a></li>
<li class="chapter" data-level="2.2.2" data-path="ifelse.html"><a href="ifelse.html#if-statement-examples"><i class="fa fa-check"></i><b>2.2.2</b> if statement examples</a></li>
<li class="chapter" data-level="2.2.3" data-path="ifelse.html"><a href="ifelse.html#single-line-if-statements"><i class="fa fa-check"></i><b>2.2.3</b> Single-line if statements</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="ifelse.html"><a href="ifelse.html#if-else-statements"><i class="fa fa-check"></i><b>2.3</b> if-else statements</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="ifelse.html"><a href="ifelse.html#if-else-if-chains"><i class="fa fa-check"></i><b>2.3.1</b> if-else-if chains</a></li>
<li class="chapter" data-level="2.3.2" data-path="ifelse.html"><a href="ifelse.html#nested-if-else-statements"><i class="fa fa-check"></i><b>2.3.2</b> Nested if-else statements</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="ifelse.html"><a href="ifelse.html#the-ifelse-function"><i class="fa fa-check"></i><b>2.4</b> The ifelse function</a></li>
<li class="chapter" data-level="2.5" data-path="ifelse.html"><a href="ifelse.html#exercises-1"><i class="fa fa-check"></i><b>2.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>3</b> Functions in R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="functions.html"><a href="functions.html#built-in-r-functions"><i class="fa fa-check"></i><b>3.1</b> Built-in R functions</a></li>
<li class="chapter" data-level="3.2" data-path="functions.html"><a href="functions.html#construction-your-own-r-functions"><i class="fa fa-check"></i><b>3.2</b> Construction your own R functions</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="functions.html"><a href="functions.html#function-definition-syntax"><i class="fa fa-check"></i><b>3.2.1</b> Function Definition Syntax</a></li>
<li class="chapter" data-level="3.2.2" data-path="functions.html"><a href="functions.html#example-1"><i class="fa fa-check"></i><b>3.2.2</b> Example 1</a></li>
<li class="chapter" data-level="3.2.3" data-path="functions.html"><a href="functions.html#example-2"><i class="fa fa-check"></i><b>3.2.3</b> Example 2</a></li>
<li class="chapter" data-level="3.2.4" data-path="functions.html"><a href="functions.html#rules-for-choosing-function-names"><i class="fa fa-check"></i><b>3.2.4</b> Rules for choosing function names</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="functions.html"><a href="functions.html#default-argument-values-in-functions"><i class="fa fa-check"></i><b>3.3</b> Default argument values in functions</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="functions.html"><a href="functions.html#example-1-1"><i class="fa fa-check"></i><b>3.3.1</b> Example 1</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="functions.html"><a href="functions.html#specifying-function-arguments-with-keywords"><i class="fa fa-check"></i><b>3.4</b> Specifying function arguments with keywords</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="functions.html"><a href="functions.html#example-1-2"><i class="fa fa-check"></i><b>3.4.1</b> Example 1</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="functions.html"><a href="functions.html#more-examples-of-writing-functions"><i class="fa fa-check"></i><b>3.5</b> More Examples of Writing Functions</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="functions.html"><a href="functions.html#example-1-passfail-from-a-weighted-average"><i class="fa fa-check"></i><b>3.5.1</b> Example 1: Pass/Fail from a Weighted Average</a></li>
<li class="chapter" data-level="3.5.2" data-path="functions.html"><a href="functions.html#example-2-1"><i class="fa fa-check"></i><b>3.5.2</b> Example 2: …</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="functions.html"><a href="functions.html#exercises-2"><i class="fa fa-check"></i><b>3.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="loops.html"><a href="loops.html"><i class="fa fa-check"></i><b>4</b> Loops in R</a>
<ul>
<li class="chapter" data-level="4.1" data-path="loops.html"><a href="loops.html#for-loops"><i class="fa fa-check"></i><b>4.1</b> For Loops</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="loops.html"><a href="loops.html#example-1-printing-the-first-5-integers"><i class="fa fa-check"></i><b>4.1.1</b> Example 1: printing the first 5 integers</a></li>
<li class="chapter" data-level="4.1.2" data-path="loops.html"><a href="loops.html#example-2-computing-10-factorial"><i class="fa fa-check"></i><b>4.1.2</b> Example 2: computing 10 factorial</a></li>
<li class="chapter" data-level="4.1.3" data-path="loops.html"><a href="loops.html#example-3-a-non-numeric-looping-variable"><i class="fa fa-check"></i><b>4.1.3</b> Example 3: a non-numeric looping variable</a></li>
<li class="chapter" data-level="4.1.4" data-path="loops.html"><a href="loops.html#example-4-first-fibonacci-numbers"><i class="fa fa-check"></i><b>4.1.4</b> Example 4: first Fibonacci numbers</a></li>
<li class="chapter" data-level="4.1.5" data-path="loops.html"><a href="loops.html#nested-for-loops"><i class="fa fa-check"></i><b>4.1.5</b> Nested for loops</a></li>
<li class="chapter" data-level="4.1.6" data-path="loops.html"><a href="loops.html#break-and-next-exiting-for-loops-and-skipping-iterations"><i class="fa fa-check"></i><b>4.1.6</b> break and next: Exiting for loops and skipping iterations</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="loops.html"><a href="loops.html#while-loops"><i class="fa fa-check"></i><b>4.2</b> While Loops</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="loops.html"><a href="loops.html#example-1-a-first-which-function"><i class="fa fa-check"></i><b>4.2.1</b> Example 1: a “first which” function</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="loops.html"><a href="loops.html#exercises-3"><i class="fa fa-check"></i><b>4.3</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>II R Data Structures</b></span></li>
<li class="chapter" data-level="5" data-path="vectors.html"><a href="vectors.html"><i class="fa fa-check"></i><b>5</b> Vectors</a>
<ul>
<li class="chapter" data-level="5.1" data-path="vectors.html"><a href="vectors.html#creating-vectors-in-r"><i class="fa fa-check"></i><b>5.1</b> Creating vectors in R</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="vectors.html"><a href="vectors.html#the-concatenate-function-c"><i class="fa fa-check"></i><b>5.1.1</b> The concatenate function <code>c()</code></a></li>
<li class="chapter" data-level="5.1.2" data-path="vectors.html"><a href="vectors.html#colon-seq-rep-creating-vectors-with-specific-patterns"><i class="fa fa-check"></i><b>5.1.2</b> colon, seq, rep: Creating vectors with specific patterns</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="vectors.html"><a href="vectors.html#subsets-of-vectors"><i class="fa fa-check"></i><b>5.2</b> Subsets of vectors</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="vectors.html"><a href="vectors.html#extracting-vector-elements"><i class="fa fa-check"></i><b>5.2.1</b> Extracting vector elements</a></li>
<li class="chapter" data-level="5.2.2" data-path="vectors.html"><a href="vectors.html#subsetting-with-logical-expressions"><i class="fa fa-check"></i><b>5.2.2</b> Subsetting with logical expressions</a></li>
<li class="chapter" data-level="5.2.3" data-path="vectors.html"><a href="vectors.html#the-which-function"><i class="fa fa-check"></i><b>5.2.3</b> The which function</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="vectors.html"><a href="vectors.html#useful-methods-for-vectors"><i class="fa fa-check"></i><b>5.3</b> Useful methods for vectors</a></li>
<li class="chapter" data-level="5.4" data-path="vectors.html"><a href="vectors.html#vectors-with-different-data-types"><i class="fa fa-check"></i><b>5.4</b> Vectors with different data types</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="vectors.html"><a href="vectors.html#explicitly-changing-the-data-types"><i class="fa fa-check"></i><b>5.4.1</b> Explicitly changing the data types</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="vectors.html"><a href="vectors.html#mathematical-operations-with-vectors"><i class="fa fa-check"></i><b>5.5</b> Mathematical operations with vectors</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="vectors.html"><a href="vectors.html#recycling-rules"><i class="fa fa-check"></i><b>5.5.1</b> Recycling rules</a></li>
<li class="chapter" data-level="5.5.2" data-path="vectors.html"><a href="vectors.html#logical-operations-with-vectors"><i class="fa fa-check"></i><b>5.5.2</b> Logical operations with vectors</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="vectors.html"><a href="vectors.html#set-operations-with-vectors"><i class="fa fa-check"></i><b>5.6</b> Set operations with vectors</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="vectors.html"><a href="vectors.html#the-function-unique"><i class="fa fa-check"></i><b>5.6.1</b> The function unique()</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="vectors.html"><a href="vectors.html#na-and-is.na-missing-values-in-r"><i class="fa fa-check"></i><b>5.7</b> NA and is.na(): missing values in R</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="vectors.html"><a href="vectors.html#the-function-is.na"><i class="fa fa-check"></i><b>5.7.1</b> The function <code>is.na()</code></a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="vectors.html"><a href="vectors.html#exercises-4"><i class="fa fa-check"></i><b>5.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="matrix.html"><a href="matrix.html"><i class="fa fa-check"></i><b>6</b> Matrices</a>
<ul>
<li class="chapter" data-level="6.1" data-path="matrix.html"><a href="matrix.html#creating-matrices-in-r"><i class="fa fa-check"></i><b>6.1</b> Creating matrices in R</a></li>
<li class="chapter" data-level="6.2" data-path="matrix.html"><a href="matrix.html#accessing-different-features-of-a-matrix"><i class="fa fa-check"></i><b>6.2</b> Accessing different features of a matrix</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="matrix.html"><a href="matrix.html#accessing-elements-of-a-matrix"><i class="fa fa-check"></i><b>6.2.1</b> Accessing elements of a matrix</a></li>
<li class="chapter" data-level="6.2.2" data-path="matrix.html"><a href="matrix.html#diagonals-of-matrices"><i class="fa fa-check"></i><b>6.2.2</b> Diagonals of Matrices</a></li>
<li class="chapter" data-level="6.2.3" data-path="matrix.html"><a href="matrix.html#naming-rows-or-columns"><i class="fa fa-check"></i><b>6.2.3</b> Naming rows or columns</a></li>
<li class="chapter" data-level="6.2.4" data-path="matrix.html"><a href="matrix.html#combining-rows-or-columns"><i class="fa fa-check"></i><b>6.2.4</b> Combining rows or columns</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="matrix.html"><a href="matrix.html#applying-functions-to-matrices"><i class="fa fa-check"></i><b>6.3</b> Applying functions to matrices</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="matrix.html"><a href="matrix.html#mathematical-operations-with-matrices"><i class="fa fa-check"></i><b>6.3.1</b> Mathematical operations with matrices</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="matrix.html"><a href="matrix.html#matrix-functionals"><i class="fa fa-check"></i><b>6.4</b> Matrix Functionals</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="matrix.html"><a href="matrix.html#functions-applied-to-each-rowcolumn"><i class="fa fa-check"></i><b>6.4.1</b> Functions applied to <strong>each</strong> row/column</a></li>
<li class="chapter" data-level="6.4.2" data-path="matrix.html"><a href="matrix.html#apply-dimension-wise-aggregation"><i class="fa fa-check"></i><b>6.4.2</b> <strong>apply()</strong>: dimension-wise aggregation</a></li>
<li class="chapter" data-level="6.4.3" data-path="matrix.html"><a href="matrix.html#using-apply-with-your-own-function"><i class="fa fa-check"></i><b>6.4.3</b> Using apply with your own function</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="matrix.html"><a href="matrix.html#exercises-5"><i class="fa fa-check"></i><b>6.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="list.html"><a href="list.html"><i class="fa fa-check"></i><b>7</b> Lists</a>
<ul>
<li class="chapter" data-level="7.1" data-path="list.html"><a href="list.html#creating-lists-in-r"><i class="fa fa-check"></i><b>7.1</b> Creating Lists in R</a></li>
<li class="chapter" data-level="7.2" data-path="list.html"><a href="list.html#accessing-list-elements"><i class="fa fa-check"></i><b>7.2</b> Accessing list elements</a></li>
<li class="chapter" data-level="7.3" data-path="list.html"><a href="list.html#working-with-lists"><i class="fa fa-check"></i><b>7.3</b> Working with lists</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="list.html"><a href="list.html#expanding-a-list-adding-more-components"><i class="fa fa-check"></i><b>7.3.1</b> Expanding a list: adding more components</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="list.html"><a href="list.html#when-are-lists-useful"><i class="fa fa-check"></i><b>7.4</b> When are lists useful?</a></li>
<li class="chapter" data-level="7.5" data-path="list.html"><a href="list.html#lapply-and-sapply-applying-functions-to-lists"><i class="fa fa-check"></i><b>7.5</b> lapply() and sapply(): Applying functions to lists</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="list.html"><a href="list.html#use-sapply-for-simpler-output"><i class="fa fa-check"></i><b>7.5.1</b> Use sapply() for simpler output</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="list.html"><a href="list.html#exercises-6"><i class="fa fa-check"></i><b>7.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="dataframe.html"><a href="dataframe.html"><i class="fa fa-check"></i><b>8</b> Data Frames</a>
<ul>
<li class="chapter" data-level="8.1" data-path="dataframe.html"><a href="dataframe.html#creating-data-frames"><i class="fa fa-check"></i><b>8.1</b> Creating Data Frames</a></li>
<li class="chapter" data-level="8.2" data-path="dataframe.html"><a href="dataframe.html#accessing-and-modifying-data-frames"><i class="fa fa-check"></i><b>8.2</b> Accessing and Modifying Data Frames</a></li>
<li class="chapter" data-level="8.3" data-path="dataframe.html"><a href="dataframe.html#subsetting-data-frames"><i class="fa fa-check"></i><b>8.3</b> Subsetting data frames</a></li>
<li class="chapter" data-level="8.4" data-path="dataframe.html"><a href="dataframe.html#exercises-7"><i class="fa fa-check"></i><b>8.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="factors.html"><a href="factors.html"><i class="fa fa-check"></i><b>9</b> Factors</a>
<ul>
<li class="chapter" data-level="9.1" data-path="factors.html"><a href="factors.html#definition-of-factors"><i class="fa fa-check"></i><b>9.1</b> Definition of Factors</a></li>
<li class="chapter" data-level="9.2" data-path="factors.html"><a href="factors.html#adding-new-levels-to-a-factor"><i class="fa fa-check"></i><b>9.2</b> Adding new levels to a factor</a></li>
<li class="chapter" data-level="9.3" data-path="factors.html"><a href="factors.html#the-table-function"><i class="fa fa-check"></i><b>9.3</b> The table() function</a></li>
<li class="chapter" data-level="9.4" data-path="factors.html"><a href="factors.html#tapply-and-aggregate"><i class="fa fa-check"></i><b>9.4</b> tapply() and aggregate</a></li>
</ul></li>
<li class="part"><span><b>III Importing and Organizing Data</b></span></li>
<li class="chapter" data-level="10" data-path="fileinput.html"><a href="fileinput.html"><i class="fa fa-check"></i><b>10</b> Reading Data Files into R</a>
<ul>
<li class="chapter" data-level="10.1" data-path="fileinput.html"><a href="fileinput.html#downloading-a-file-locally"><i class="fa fa-check"></i><b>10.1</b> Downloading a file locally</a></li>
<li class="chapter" data-level="10.2" data-path="fileinput.html"><a href="fileinput.html#opening-a-remote-file-using-read.table"><i class="fa fa-check"></i><b>10.2</b> Opening a remote file using read.table()</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="datawrangling.html"><a href="datawrangling.html"><i class="fa fa-check"></i><b>11</b> Data Wrangling</a>
<ul>
<li class="chapter" data-level="11.1" data-path="datawrangling.html"><a href="datawrangling.html#the-nycflights13-data"><i class="fa fa-check"></i><b>11.1</b> The nycflights13 data</a></li>
<li class="chapter" data-level="11.2" data-path="datawrangling.html"><a href="datawrangling.html#exploring-the-dataset"><i class="fa fa-check"></i><b>11.2</b> Exploring the Dataset</a></li>
<li class="chapter" data-level="11.3" data-path="datawrangling.html"><a href="datawrangling.html#summarizing-each-variable"><i class="fa fa-check"></i><b>11.3</b> Summarizing each variable</a></li>
<li class="chapter" data-level="11.4" data-path="datawrangling.html"><a href="datawrangling.html#using-the-dplyr-package"><i class="fa fa-check"></i><b>11.4</b> Using the dplyr package</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An Introduction to R programming</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="intro" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Chapter 1</span> Getting Started<a href="intro.html#intro" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="r-and-rstudio" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> <span style="color:#D96716"><strong>R</strong></span> and <span style="color:#D96716"><strong>RStudio</strong></span><a href="intro.html#r-and-rstudio" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p><strong>R</strong></p>
<ul>
<li><span style="color:#D96716"><strong>Free</strong></span> software developed by R Core Team</li>
<li>Available at <a href="https://www.r-project.org/">https://www.r-project.org/</a></li>
<li>Software and packages are managed by the nonprofit organization “R Foundation”</li>
</ul></li>
<li><p><strong>RStudio</strong></p>
<ul>
<li>An <strong>integrated development environment</strong> (IDE) for programming in <strong>R</strong>.</li>
<li>Provides many add-ons to <strong>R</strong> available in a single interface.</li>
<li>Developed by RStudio, Inc.</li>
<li>Available in both <strong>free</strong> (AGPLv3) and commercial editions at <a href="https://posit.co/download/rstudio-desktop/#download">https://posit.co/download/rstudio-desktop/#download</a></li>
</ul></li>
</ul>
<hr />
<ul>
<li><p><strong>R</strong> and <strong>RStudio</strong> are separate things.</p>
<ul>
<li>You should install R first before RStudio</li>
</ul></li>
<li><p><strong>R</strong></p>
<ul>
<li>Download and install R at <a href="https://cloud.r-project.org/">https://cloud.r-project.org/</a></li>
</ul></li>
<li><p><strong>RStudio</strong></p>
<ul>
<li>Download and install the open source version of RStudio Desktop at <a href="https://rstudio.com/products/rstudio/download/#download">https://rstudio.com/products/rstudio/download/#download</a></li>
</ul></li>
<li><p>When you open <strong>Rstudio</strong>, it should look something like:
<img src="Figures/RStudio1.png" width="800" height="450" /></p></li>
<li><p>The <strong>left-hand panel</strong> of RStudio is where you can type in <strong>R</strong> code directly.</p></li>
<li><p>For example, we can treat R as a <strong>calculator</strong> and add and multiply numbers by typing them directly in the left-hand panel.</p></li>
<li><p>Typing and running <strong>R</strong> code line-by-line like this is referred to as using <strong>R</strong> in <strong>interactive mode</strong>.</p></li>
<li><p>When writing more complex code that you can reuse, it is usually better
to write it in a <strong>separate file</strong> such as an <strong>R script</strong> (this type of file ends in .R).</p></li>
<li><p>To create a new <strong>R</strong> script, go to <strong>File –&gt; New File –&gt; R script</strong> in Rstudio.</p></li>
</ul>
<p><img src="Figures/RStudio3.png" width="750" height="400" /></p>
<hr />
<ul>
<li><p>As an example of writing and running <strong>R scripts</strong>, let’s write an <strong>R</strong> script that will simply print
out the message <strong>“Hello World”</strong> whenever we run the script.</p></li>
<li><p>To do this we just write the following <strong>R</strong> code in
the empty <strong>R</strong> script/l</p></li>
</ul>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="intro.html#cb1-1" tabindex="-1"></a><span class="st">&quot;Hello World&quot;</span></span></code></pre></div>
<p><img src="Figures/RStudio4.png" width="850" height="400" /></p>
<ul>
<li>Before running the script, you can save the file as <strong>“hello_world.R”</strong>.</li>
</ul>
<p><img src="Figures/RStudio5.png" /></p>
<ul>
<li><p>To run the script, just click the <strong>“Run”</strong> button located at the top right of your
<strong>R</strong> script.</p></li>
<li><p>The message “Hello World” should appear in the <strong>R</strong> console below:
<img src="Figures/RStudio6.png" width="700" height="400" /></p></li>
</ul>
</div>
<div id="an-extended-example-the-nyc-flights-data" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> An Extended Example: the NYC flights data<a href="intro.html#an-extended-example-the-nyc-flights-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>To illustrate some of the capabilities of R for exploring and summarizing data, we will look at the <strong>“NYC flights”</strong> dataset.</p></li>
<li><p>This is a dataset that contains information on flights that departed from the New York City region in 2013.</p></li>
<li><p>This dataset is available in an R package called <strong>“nycflights13”</strong></p></li>
</ul>
<div id="installing-r-packages" class="section level3 hasAnchor" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> Installing R packages<a href="intro.html#installing-r-packages" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>To use an R package, you must first <strong>install it</strong>.</p></li>
<li><p>Installing the <code>nycflights13</code> package can be done with the following command:</p></li>
</ul>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="intro.html#cb2-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;nycflights13&quot;</span>)</span></code></pre></div>
<ul>
<li>Note that, if a package has been installed previously, you don’t need to install it again in order to use it.</li>
</ul>
<p>–</p>
<ul>
<li>Once an R package has been installed, you can <strong>“load”</strong> it into your R session with the <code>library</code> function:</li>
</ul>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="intro.html#cb3-1" tabindex="-1"></a><span class="fu">library</span>(nycflights13)</span></code></pre></div>
<ul>
<li>Running the <code>library</code> command just makes the datasets in the <code>nycflights13</code> package <strong>available</strong> for
you to use in your R session.</li>
</ul>
</div>
<div id="nyc-flights-data-details" class="section level3 hasAnchor" number="1.2.2">
<h3><span class="header-section-number">1.2.2</span> NYC flights data details<a href="intro.html#nyc-flights-data-details" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>There are 5 datasets in the <code>nycflights13</code> package: <code>airlines</code>, <code>airports</code>, <code>flights</code>, <code>planes</code>, <code>weather</code></p></li>
<li><p>Let’s first look at the <code>planes</code> dataset.</p></li>
<li><p>This dataset is stored as a <strong>data frame</strong> in R.</p>
<ul>
<li>Using a <strong>dataframe</strong> is the most standard way to store a dataset in R</li>
</ul></li>
<li><p>An R data frame has a certain number of <strong>rows</strong> (which usually represent different observations)
and <strong>columns</strong> (which usually represent different variables).</p>
<ul>
<li><p>I will refer to the variables in a data frame as <strong>“data variables”</strong>.</p></li>
<li><p>This is to distinguish it from <strong>R variables</strong> that you can create in your R session.</p></li>
</ul></li>
</ul>
<hr />
<ul>
<li><p>The <code>planes</code> data frame has <strong>3322 rows and 9 columns</strong>.</p></li>
<li><p>The number of rows and columns of a data frame can be found by using the <code>dim</code> function.</p></li>
</ul>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="intro.html#cb4-1" tabindex="-1"></a><span class="fu">dim</span>(planes)</span></code></pre></div>
<pre><code>## [1] 3322    9</code></pre>
<ul>
<li><p>Each row of the <code>planes</code> data frame contains information about a <strong>specific airplane</strong>.</p></li>
<li><p>You can look at the contents of the <strong>first 6 rows</strong> of a data frame by using the <code>head</code> function</p></li>
</ul>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="intro.html#cb6-1" tabindex="-1"></a><span class="fu">head</span>(planes)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 9
##   tailnum  year type               manufacturer model engines seats speed engine
##   &lt;chr&gt;   &lt;int&gt; &lt;chr&gt;              &lt;chr&gt;        &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; 
## 1 N10156   2004 Fixed wing multi … EMBRAER      EMB-…       2    55    NA Turbo…
## 2 N102UW   1998 Fixed wing multi … AIRBUS INDU… A320…       2   182    NA Turbo…
## 3 N103US   1999 Fixed wing multi … AIRBUS INDU… A320…       2   182    NA Turbo…
## 4 N104UW   1999 Fixed wing multi … AIRBUS INDU… A320…       2   182    NA Turbo…
## 5 N10575   2002 Fixed wing multi … EMBRAER      EMB-…       2    55    NA Turbo…
## 6 N105UW   1999 Fixed wing multi … AIRBUS INDU… A320…       2   182    NA Turbo…</code></pre>
<ul>
<li><p>The <code>planes</code> data frame has 9 variables.</p>
<ul>
<li><code>tailnum</code>: The tail number of the plane. This number is a unique identifier for each plane.</li>
<li><code>year</code>: The year the plane manufactured.</li>
<li><code>type</code>: The type of plane.</li>
<li><code>manufacturer</code>: The manufacturer of the plane.</li>
<li><code>model</code>: The model of the plane.</li>
<li><code>engines</code>: The number of engines that the plane has.</li>
<li><code>seats</code>: The number of seats that the plane has.</li>
<li><code>speed</code>: Average cruising speed in mph.</li>
<li><code>engine</code>: Type of engine.</li>
</ul></li>
<li><p>Running the command <code>help(planes)</code> can give <strong>more information</strong> about this dataset.</p></li>
</ul>
</div>
<div id="summarizing-specific-data-variables" class="section level3 hasAnchor" number="1.2.3">
<h3><span class="header-section-number">1.2.3</span> Summarizing specific data variables<a href="intro.html#summarizing-specific-data-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>You can <strong>access</strong> individual variables from <code>planes</code> by using the <code>$</code> operator.</p></li>
<li><p>For example, if we want to <strong>assign</strong> the values in the <code>year</code> column into a
new <strong>R variable</strong> named plane_year, we do the following:</p></li>
</ul>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="intro.html#cb8-1" tabindex="-1"></a>plane_year <span class="ot">&lt;-</span> planes<span class="sc">$</span>year</span></code></pre></div>
<ul>
<li><p>After running the above line of code, <code>plane_year</code> is an R <code>vector</code> that has 3322 elements.</p></li>
<li><p>The <code>length</code> function tells us how many elements are in a vector</p></li>
</ul>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="intro.html#cb9-1" tabindex="-1"></a><span class="fu">length</span>(plane_year)</span></code></pre></div>
<pre><code>## [1] 3322</code></pre>
<ul>
<li><p>We can look at the <strong>first x elements</strong> of <code>plane_year</code> by using the syntax <code>plane_year[1:x]</code>.</p></li>
<li><p>For example, let’s look at the first 5 elements of <code>plane_year</code>:</p></li>
</ul>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="intro.html#cb11-1" tabindex="-1"></a>plane_year[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>## [1] 2004 1998 1999 1999 2002</code></pre>
<hr />
<ul>
<li>We can get a count of how many times each value of <code>year</code> occurs by using the <code>table</code> function</li>
</ul>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="intro.html#cb13-1" tabindex="-1"></a><span class="fu">table</span>(plane_year)</span></code></pre></div>
<pre><code>## plane_year
## 1956 1959 1963 1965 1967 1968 1972 1973 1974 1975 1976 1977 1978 1979 1980 1983 
##    1    2    2    1    1    1    1    1    1    3    3    2    2    4    4    1 
## 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 
##    5   23   17   40   75   60   90  108  109   59   48   54   55   74  174  206 
## 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 
##  244  284  212  150  192  162  126  123  147   84   48   66   95   92</code></pre>
<ul>
<li><p>The above <strong>R output</strong> says that <strong>147</strong> of the planes in the <code>planes</code> data frame were manufactured in 2008 and <strong>92</strong> planes in the <code>planes</code> data frame were manufactured in 2013.</p></li>
<li><p>The <code>table</code> function is useful for data variables that have a relatively small number of distinct values.</p></li>
<li><p>For <strong>numeric</strong> data variables that are better thought of as continuous variables, one often <strong>summarizes</strong>
these data variables by looking at things like the <strong>mean</strong>, <strong>median</strong>, or <strong>standard deviation</strong>.</p></li>
<li><p>Using the <code>summary</code> function on a single data variable gives you a useful <strong>“six-number summary”</strong> about that data variable:</p></li>
</ul>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="intro.html#cb15-1" tabindex="-1"></a><span class="fu">summary</span>(planes<span class="sc">$</span>seats)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     2.0   140.0   149.0   154.3   182.0   450.0</code></pre>
<hr />
<ul>
<li><p>Another dataset available in the <code>nycflights13</code> package is the <code>weather</code> data frame.</p></li>
<li><p>This data frame has <strong>26115 rows</strong> and <strong>15 columns</strong>.</p></li>
</ul>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="intro.html#cb17-1" tabindex="-1"></a><span class="fu">dim</span>( weather )</span></code></pre></div>
<pre><code>## [1] 26115    15</code></pre>
<ul>
<li>You can output all of the data variable names by using the <code>names</code> function:</li>
</ul>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="intro.html#cb19-1" tabindex="-1"></a><span class="fu">names</span>( weather )</span></code></pre></div>
<pre><code>##  [1] &quot;origin&quot;     &quot;year&quot;       &quot;month&quot;      &quot;day&quot;        &quot;hour&quot;      
##  [6] &quot;temp&quot;       &quot;dewp&quot;       &quot;humid&quot;      &quot;wind_dir&quot;   &quot;wind_speed&quot;
## [11] &quot;wind_gust&quot;  &quot;precip&quot;     &quot;pressure&quot;   &quot;visib&quot;      &quot;time_hour&quot;</code></pre>
<ul>
<li>One of the data variables is <code>month</code>. This just records what <strong>month</strong> the weather observation
was made in</li>
</ul>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="intro.html#cb21-1" tabindex="-1"></a><span class="fu">table</span>( weather<span class="sc">$</span>month )</span></code></pre></div>
<pre><code>## 
##    1    2    3    4    5    6    7    8    9   10   11   12 
## 2226 2010 2227 2159 2232 2160 2228 2217 2159 2212 2141 2144</code></pre>
</div>
<div id="subsetting-data" class="section level3 hasAnchor" number="1.2.4">
<h3><span class="header-section-number">1.2.4</span> Subsetting Data<a href="intro.html#subsetting-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>An important part of many data analyses is looking at data summaries of specific <strong>subsets</strong> of interest.</p></li>
<li><p>To create a <strong>new data frame</strong> which is a subset of the original data frame, you can use the <code>subset</code> function.</p></li>
<li><p>For example, if we only want to look at weather in the <strong>month of January</strong>, we can a new data frame
which only contains January observations (where <code>month</code> equals 1)</p></li>
</ul>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="intro.html#cb23-1" tabindex="-1"></a>JanuaryWeather <span class="ot">&lt;-</span> <span class="fu">subset</span>(weather, month<span class="sc">==</span><span class="dv">1</span>)</span></code></pre></div>
<ul>
<li>The <code>JanuaryWeather</code> data frame has <strong>2226</strong> observations</li>
</ul>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="intro.html#cb24-1" tabindex="-1"></a><span class="fu">dim</span>( JanuaryWeather )</span></code></pre></div>
<pre><code>## [1] 2226   15</code></pre>
<ul>
<li>The <strong>average temperature</strong> over the month of January is</li>
</ul>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="intro.html#cb26-1" tabindex="-1"></a><span class="fu">mean</span>( JanuaryWeather<span class="sc">$</span>temp )</span></code></pre></div>
<pre><code>## [1] 35.63566</code></pre>
<hr />
<ul>
<li><p>One can take more complex subsets of a data frame by using <strong>logical expressions</strong>
in the second argument of the <code>subset</code> function.</p></li>
<li><p>For example, if you wanted to create a data frame that only has observations in <strong>February</strong>
that are <strong>above 40 degrees</strong> Fahrenheit, you could use the following code:</p></li>
</ul>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="intro.html#cb28-1" tabindex="-1"></a>FebAbove40 <span class="ot">&lt;-</span> <span class="fu">subset</span>(weather, month<span class="sc">==</span><span class="dv">2</span> <span class="sc">&amp;</span> temp <span class="sc">&gt;</span> <span class="dv">40</span>)</span></code></pre></div>
</div>
<div id="plotting-data" class="section level3 hasAnchor" number="1.2.5">
<h3><span class="header-section-number">1.2.5</span> Plotting Data<a href="intro.html#plotting-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p><strong>R</strong> has many functions that can aid data visualization.</p></li>
<li><p>For example, you can create a simple histogram of the temperature variable by using
the vector <code>weather$temp</code> inside the <code>hist</code> function:</p></li>
</ul>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="intro.html#cb29-1" tabindex="-1"></a><span class="fu">hist</span>( weather<span class="sc">$</span>temp )</span></code></pre></div>
<p><img src="01-intro_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<ul>
<li>You could create <strong>separate boxplots</strong> of temperature for each month by using the modeling syntax
<code>temp ~ month</code> within the boxplot function:</li>
</ul>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="intro.html#cb30-1" tabindex="-1"></a><span class="do">## Use x-axis label &quot;Month&quot; and y-axis label &quot;Temperature&quot; in the figure:</span></span>
<span id="cb30-2"><a href="intro.html#cb30-2" tabindex="-1"></a><span class="fu">boxplot</span>(temp <span class="sc">~</span> month, <span class="at">data=</span>weather, <span class="at">xlab=</span><span class="st">&quot;Month&quot;</span>,</span>
<span id="cb30-3"><a href="intro.html#cb30-3" tabindex="-1"></a>        <span class="at">ylab=</span><span class="st">&quot;Temperature&quot;</span>)</span></code></pre></div>
<p><img src="01-intro_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
</div>
</div>
<div id="using-r-as-a-calculator" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Using R as a calculator<a href="intro.html#using-r-as-a-calculator" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>When first starting with <strong>R</strong>, it can be helpful to note that <strong>R</strong> can be used as a basic <strong>calculator</strong>.</p></li>
<li><p>For example, if we just type in <code>42 + 17</code> into the R console, it should print out the sum:</p></li>
</ul>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="intro.html#cb31-1" tabindex="-1"></a><span class="dv">42</span> <span class="sc">+</span> <span class="dv">17</span> </span></code></pre></div>
<pre><code>## [1] 59</code></pre>
<ul>
<li>We can compute the square root of 243, <span class="math inline">\(1.56^{124}\)</span>, and <span class="math inline">\(7.21 \times 8^{4}\)</span>, just by typing these expressions into the <strong>R console</strong></li>
</ul>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="intro.html#cb33-1" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="dv">243</span>)</span></code></pre></div>
<pre><code>## [1] 15.58846</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="intro.html#cb35-1" tabindex="-1"></a><span class="fl">1.56</span><span class="sc">*</span><span class="dv">124</span></span></code></pre></div>
<pre><code>## [1] 193.44</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="intro.html#cb37-1" tabindex="-1"></a><span class="fl">7.21</span><span class="sc">*</span><span class="dv">8</span><span class="sc">^</span><span class="dv">4</span></span></code></pre></div>
<pre><code>## [1] 29532.16</code></pre>
</div>
<div id="variables-in-r" class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> Variables in R<a href="intro.html#variables-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>When starting to work with more complicated mathematical operations in <strong>R</strong>, it is often useful to
store intermediate values in <strong>named variables</strong> instead of using <strong>R</strong> as a calculator in interactive mode.</p></li>
<li><p>For example, the following <strong>R</strong> code creates the variables <code>x, y, z</code> and assigns
them the values <span class="math inline">\((42 + 17)\sqrt{43}\)</span>, <span class="math inline">\(7.21(8^{4}) + \ln(2.34)\)</span>, and<br />
<span class="math inline">\((42 + 17)\sqrt{43}/[ 7.21(8^{4}) + \ln(2.34) ]\)</span> respectively.</p></li>
</ul>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="intro.html#cb39-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> (<span class="dv">42</span> <span class="sc">+</span> <span class="dv">17</span>)<span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">43</span>)</span>
<span id="cb39-2"><a href="intro.html#cb39-2" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fl">7.21</span><span class="sc">*</span><span class="dv">8</span><span class="sc">^</span><span class="dv">4</span> <span class="sc">+</span> <span class="fu">log</span>(<span class="fl">2.34</span>)</span>
<span id="cb39-3"><a href="intro.html#cb39-3" tabindex="-1"></a>z <span class="ot">&lt;-</span> x<span class="sc">/</span>y</span>
<span id="cb39-4"><a href="intro.html#cb39-4" tabindex="-1"></a>z  <span class="do">## print out the value of z</span></span></code></pre></div>
<pre><code>## [1] 0.01310022</code></pre>
<ul>
<li><p>Here, <code>x</code>, <code>y</code>, and <code>z</code> are examples of <strong>variables</strong>.</p></li>
<li><p>The pair of characters <code>&lt;-</code> used together is known as the <strong>assignment operator</strong> in <strong>R</strong>.
<code>x &lt;- 2</code> assigns the value <code>2</code> to the variable <code>x</code>.</p></li>
</ul>
<hr />
<ul>
<li><p>In general, a <strong>variable</strong> is the <strong>named storage</strong> of a value (or an object) in memory.</p></li>
<li><p>Why do we need variables?</p>
<ul>
<li>To <strong>reuse</strong> the same value later on.</li>
<li>To <strong>generalize</strong> an expression to use in many cases.</li>
</ul></li>
<li><p>How to use variables in <strong>R</strong>?</p>
<ul>
<li><p>To set the value of a variable, use <strong>assignment</strong> operator <code>&lt;-</code></p></li>
<li><p>To use the value, simply use the <strong>variable name</strong> as if it were its stored value.</p></li>
</ul></li>
<li><p>For example, …</p></li>
</ul>
<div id="rules-for-choosing-variable-names-in-r" class="section level3 hasAnchor" number="1.4.1">
<h3><span class="header-section-number">1.4.1</span> Rules for choosing <strong>variable names</strong> in R<a href="intro.html#rules-for-choosing-variable-names-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Variables can be named however you want as long as you follow the
several variable-naming rules that R has.</p></li>
<li><p>In <strong>R</strong> variable names can include the following:</p>
<ul>
<li><strong>letters</strong>: A-Z a-z</li>
<li><strong>digits</strong>: 0-9</li>
<li><strong>underscore and period</strong>: _ .</li>
</ul></li>
<li><p>Additional rules:</p>
<ul>
<li>Variable names <strong>must start with letters or a period (not underscore or digits)</strong></li>
<li>If a variable name starts with a <strong>period</strong>, it <strong>cannot</strong> be followed by a <strong>number</strong>.</li>
<li>Variable names are <strong>case sensitive</strong>.</li>
</ul></li>
<li><p>The following tables shows examples of <strong>valid</strong> and <strong>invalid</strong> variable names in R</p></li>
</ul>
<table>
<thead>
<tr class="header">
<th align="center">Valid</th>
<th align="center">Invalid</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">i</td>
<td align="center">2things</td>
</tr>
<tr class="even">
<td align="center">my_variable</td>
<td align="center">location@</td>
</tr>
<tr class="odd">
<td align="center">answer42</td>
<td align="center">_user.name</td>
</tr>
<tr class="even">
<td align="center">.name</td>
<td align="center">.3rd</td>
</tr>
</tbody>
</table>
<ul>
<li><p>While you are free to choose variable names however you like as long as you follow the variable-naming rules of <strong>R</strong>, making variable names <strong>descriptive</strong> is highly <strong>recommended</strong>.</p></li>
<li><p><strong>Descriptive</strong> variable names make it easier to read code. This is very helpful if:</p>
<ul>
<li>You are sharing your code or</li>
<li>Looking back at code you wrote many weeks/months ago</li>
</ul></li>
<li><p>Using a <strong>consistent</strong> convention for naming variables is recommended:</p></li>
</ul>
<p><a href="https://r4ds.had.co.nz/workflow-basics.html" class="uri">https://r4ds.had.co.nz/workflow-basics.html</a></p>
</div>
<div id="variable-assignment" class="section level3 hasAnchor" number="1.4.2">
<h3><span class="header-section-number">1.4.2</span> Variable Assignment<a href="intro.html#variable-assignment" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Variables can be assigned using either <code>&lt;-</code> or <code>=</code></li>
</ul>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="intro.html#cb41-1" tabindex="-1"></a>x <span class="ot">=</span> <span class="dv">123</span>    <span class="co"># Use = to assign a variable</span></span>
<span id="cb41-2"><a href="intro.html#cb41-2" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="dv">123</span>   <span class="co"># Or use &lt;- to assign a variable</span></span></code></pre></div>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="intro.html#cb42-1" tabindex="-1"></a>x   <span class="co"># Retrieve the value of x</span></span></code></pre></div>
<pre><code>## [1] 123</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="intro.html#cb44-1" tabindex="-1"></a>y   <span class="co"># Retrieve the value of y</span></span></code></pre></div>
<pre><code>## [1] 123</code></pre>
<ul>
<li><p>The pair of characters <code>&lt;-</code> is the classic symbol used for variable assignment in <strong>R</strong>.</p></li>
<li><p>The use of <code>&lt;-</code> instead of <code>=</code> is often recommended in <strong>R</strong> style guides:</p>
<ul>
<li><a href="http://adv-r.had.co.nz/Style.html" class="uri">http://adv-r.had.co.nz/Style.html</a></li>
</ul></li>
</ul>
<hr />
<ul>
<li><p><code>&lt;-</code> and <code>=</code> will work the same if they are both
used in the “usual way” (when assigning variables within
or outside of a function).</p></li>
<li><p>One exception, is when used inside a <strong>function call</strong>. For example, if we use <code>=</code> in the function <code>sd(x)</code>:</p></li>
</ul>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="intro.html#cb46-1" tabindex="-1"></a><span class="fu">sd</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>)) <span class="co"># only sets the argument x in sd(x) to (1,2,3,4,5)</span></span></code></pre></div>
<pre><code>## [1] 1.581139</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="intro.html#cb48-1" tabindex="-1"></a><span class="co">#x      ## will return an error if we try to print x</span></span></code></pre></div>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="intro.html#cb49-1" tabindex="-1"></a><span class="fu">sd</span>(x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>)) <span class="co"># This actually assigns the vector (1,2,3,4,5) to x</span></span></code></pre></div>
<pre><code>## [1] 1.581139</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="intro.html#cb51-1" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 1 2 3 4 5</code></pre>
<ul>
<li><p>However, using something like <code>sd(x &lt;- c(1,2,3,4,5))</code> where we assign variables in a function call is not really done that often.</p></li>
<li><p>It is <strong>not common</strong> to assign variables in a function call (I never do it).</p></li>
<li><p>Whenever, using a function <code>f</code> with a keyword such as <code>x</code>, you will generally
want to call that function using <code>f(x = ...)</code></p></li>
<li><p>So, in my opinion, there is not really a strong reason to prefer using <code>&lt;-</code> over <code>=</code> for assignment.</p></li>
<li><p>There are other justifications for using <code>&lt;-</code> such as the ability
to do assignment from the left by using the reverse symbol <code>-&gt;</code></p></li>
</ul>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="intro.html#cb53-1" tabindex="-1"></a><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>) <span class="ot">-&gt;</span> a <span class="co"># Using c(1,2,3,4) = a will not work!  </span></span>
<span id="cb53-2"><a href="intro.html#cb53-2" tabindex="-1"></a>a</span></code></pre></div>
<pre><code>## [1] 1 2 3 4</code></pre>
</div>
<div id="types-of-variables" class="section level3 hasAnchor" number="1.4.3">
<h3><span class="header-section-number">1.4.3</span> Types of variables<a href="intro.html#types-of-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Variables can be used to store <strong>different types</strong> of values.</p></li>
<li><p>Common types include numeric, text, and logical values.</p></li>
</ul>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="intro.html#cb55-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fl">3.2</span></span>
<span id="cb55-2"><a href="intro.html#cb55-2" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 3.2</code></pre>
<ul>
<li><p>Here, <code>x</code> is actually a <strong>vector</strong> (basically a collection of elements storing the same type of data).</p></li>
<li><p>It is a vector of <strong>length one</strong> (i.e., it only has one element).</p></li>
<li><p>This is the reason why you see <code>[1]</code> printed out next to the number 3.2.</p>
<ul>
<li>This means that the <strong>first element</strong> of the vector <code>x</code> is <span class="math inline">\(3.2\)</span>.</li>
</ul></li>
<li><p><strong>R</strong> treats every variable as some type of collection (e.g., vectors, matrices, lists, etc.).</p>
<ul>
<li>There are no separate data types in <strong>R</strong> for individual numbers.</li>
</ul></li>
<li><p>The elements in a vector can have different <strong>types</strong> (or modes).</p></li>
<li><p>You can find the types of the elements in a vector by using the
function <strong>typeof</strong></p></li>
</ul>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="intro.html#cb57-1" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">1743</span>)</span>
<span id="cb57-2"><a href="intro.html#cb57-2" tabindex="-1"></a><span class="fu">typeof</span>(y)  <span class="co"># double and integer are the two numeric types </span></span></code></pre></div>
<pre><code>## [1] &quot;double&quot;</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="intro.html#cb59-1" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="co"># R automatically treats every number as double</span></span>
<span id="cb59-2"><a href="intro.html#cb59-2" tabindex="-1"></a>z</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="intro.html#cb61-1" tabindex="-1"></a><span class="fu">typeof</span>(z)</span></code></pre></div>
<pre><code>## [1] &quot;double&quot;</code></pre>
<ul>
<li>The other common types for the elements in a vector include
<ul>
<li><strong>logical</strong> (TRUE or FALSE) values</li>
<li><strong>character</strong> basically text, e.g., “hello”, “car”, …</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="intro.html#cb63-1" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="cn">TRUE</span></span>
<span id="cb63-2"><a href="intro.html#cb63-2" tabindex="-1"></a><span class="fu">typeof</span>(y)   </span></code></pre></div>
<pre><code>## [1] &quot;logical&quot;</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="intro.html#cb65-1" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="st">&quot;dog&quot;</span> <span class="co"># to define a character variable, place it inside quotes</span></span>
<span id="cb65-2"><a href="intro.html#cb65-2" tabindex="-1"></a><span class="fu">typeof</span>(z)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<ul>
<li>We will discuss these types in more detail later on when
we discuss <strong>vectors</strong>, <strong>matrices</strong>, and <strong>lists</strong>.</li>
</ul>
</div>
</div>
<div id="r-operations-with-numbers" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> R Operations with numbers<a href="intro.html#r-operations-with-numbers" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>As we mentioned before, …</li>
</ul>
<table>
<thead>
<tr class="header">
<th align="center">Operator</th>
<th align="center">Meaning</th>
<th align="center">Example</th>
<th align="center">Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">+</td>
<td align="center">addition</td>
<td align="center">5 + 8</td>
<td align="center">13</td>
</tr>
<tr class="even">
<td align="center">-</td>
<td align="center">subtraction</td>
<td align="center">90 - 10</td>
<td align="center">80</td>
</tr>
<tr class="odd">
<td align="center">*</td>
<td align="center">multiplication</td>
<td align="center">4 * 7</td>
<td align="center">28</td>
</tr>
<tr class="even">
<td align="center">/</td>
<td align="center">division</td>
<td align="center">7 / 2</td>
<td align="center">3.5</td>
</tr>
<tr class="odd">
<td align="center">%%</td>
<td align="center">remainder</td>
<td align="center">7 %% 2</td>
<td align="center">1</td>
</tr>
<tr class="even">
<td align="center">^</td>
<td align="center">exponent</td>
<td align="center">3 ^ 4</td>
<td align="center">81</td>
</tr>
<tr class="odd">
<td align="center">**</td>
<td align="center">exponent</td>
<td align="center">3 ** 4</td>
<td align="center">81</td>
</tr>
</tbody>
</table>
<ul>
<li>R operations with numbers have similar <strong>precedence rules</strong> to arithmetic operations</li>
</ul>
<table>
<colgroup>
<col width="27%" />
<col width="51%" />
<col width="20%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Operator</th>
<th align="center">Description</th>
<th align="center">Precedence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">+, -</td>
<td align="center">addition and subtraction</td>
<td align="center">low</td>
</tr>
<tr class="even">
<td align="center">*, /, %%</td>
<td align="center">multiplication, division, remainder</td>
<td align="center">…</td>
</tr>
<tr class="odd">
<td align="center">**, ^</td>
<td align="center">exponentiation</td>
<td align="center">…</td>
</tr>
<tr class="even">
<td align="center">(expressions…)</td>
<td align="center">Parenthesis</td>
<td align="center">high</td>
</tr>
</tbody>
</table>
<ul>
<li>Examples of operation <strong>precedence</strong> can be seen when typing the following
expressions into the <strong>R</strong> console:</li>
</ul>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="intro.html#cb67-1" tabindex="-1"></a><span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span><span class="dv">3</span> <span class="sc">^</span> <span class="dv">4</span> <span class="co"># exponentiation &gt; mult/div &gt; add/sub</span></span></code></pre></div>
<pre><code>## [1] 163</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="intro.html#cb69-1" tabindex="-1"></a>(<span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> ) <span class="sc">*</span><span class="dv">3</span> <span class="sc">^</span> <span class="dv">4</span> <span class="co"># parenthesis &gt; exponentiation</span></span></code></pre></div>
<pre><code>## [1] 243</code></pre>
</div>
<div id="brief-introduction-to-vectors-in-r" class="section level2 hasAnchor" number="1.6">
<h2><span class="header-section-number">1.6</span> Brief introduction to vectors in R<a href="intro.html#brief-introduction-to-vectors-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>The vector is probably the most fundamental data structure in R.</p></li>
<li><p>A vector is essentially a <strong>collection</strong> of elements that all have the same “type”.</p>
<ul>
<li><p>For example, a vector can be composed of a collection of numbers or a collection of characters.</p></li>
<li><p>However, a vector cannot contain both numbers and characters.</p></li>
</ul></li>
</ul>
<hr />
<ul>
<li><p>As an example, we can create a vector named <code>x</code> that contains the numbers 1, 7, and 4.</p>
<ul>
<li>This is done with the following <strong>R</strong> code:</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="intro.html#cb71-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">7</span>, <span class="dv">4</span>)</span></code></pre></div>
<ul>
<li><p>The variable <code>x</code> is a <strong>vector of length 3</strong>. The first element of <code>x</code> is 1, the second element of <code>x</code> is 7,
and the third element of <code>x</code> is 4.</p></li>
<li><p>You can <strong>access</strong> elements of the vector <code>x</code> by using the <code>[i]</code> syntax.</p></li>
<li><p>For example, if you wanted to look at the second element of <code>x</code> you would use:</p></li>
</ul>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="intro.html#cb72-1" tabindex="-1"></a>x[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] 7</code></pre>
<hr />
<ul>
<li><p>For vectors that contain numeric values, <strong>R</strong> has many built-in functions that can compute
<strong>summary statistics</strong> about the numbers the vector.</p></li>
<li><p>For example, if we create the vector <code>y</code> that has values 1, 3, 10, 8,</p></li>
</ul>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="intro.html#cb74-1" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">10</span>, <span class="dv">8</span>)</span></code></pre></div>
<p>then we can easily compute the <strong>minimum, median, maximum, and standard deviation</strong> of this vector with the following R code:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="intro.html#cb75-1" tabindex="-1"></a><span class="fu">min</span>(y)     <span class="do">## minimum of y</span></span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="intro.html#cb77-1" tabindex="-1"></a><span class="fu">median</span>(y)  <span class="do">## median of y</span></span></code></pre></div>
<pre><code>## [1] 5.5</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="intro.html#cb79-1" tabindex="-1"></a><span class="fu">max</span>(y)     <span class="do">## maximum of y</span></span></code></pre></div>
<pre><code>## [1] 10</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="intro.html#cb81-1" tabindex="-1"></a><span class="fu">sd</span>(y)      <span class="do">## standard deviation of y</span></span></code></pre></div>
<pre><code>## [1] 4.203173</code></pre>
<hr />
<ul>
<li><p>As we saw in the <code>nycflights</code> example, when we extract a data variable from a data frame, <strong>R</strong>
returns the data variable as a <strong>vector</strong>.</p></li>
<li><p>For example, if we extract the <code>seats</code> variable from the <code>planes</code> data frame and assign it to
a variable named <code>num_seats</code>, then <code>num_seats</code> will be a numeric vector</p></li>
</ul>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="intro.html#cb83-1" tabindex="-1"></a>num_seats <span class="ot">&lt;-</span> planes<span class="sc">$</span>seats</span></code></pre></div>
<ul>
<li>The vector <code>num_seats</code> has 3322 elements in it:</li>
</ul>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="intro.html#cb84-1" tabindex="-1"></a><span class="fu">length</span>( num_seats )</span></code></pre></div>
<pre><code>## [1] 3322</code></pre>
<ul>
<li>The 10th element of <code>num_seats</code> is 182:</li>
</ul>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="intro.html#cb86-1" tabindex="-1"></a>num_seats[<span class="dv">10</span>]</span></code></pre></div>
<pre><code>## [1] 182</code></pre>
<ul>
<li>The <strong>mean</strong> of the elements in <code>num_seats</code> is 154.3</li>
</ul>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="intro.html#cb88-1" tabindex="-1"></a><span class="fu">mean</span>(num_seats)</span></code></pre></div>
<pre><code>## [1] 154.3164</code></pre>
<p>and the largest number inside the <code>num_seats</code> vector is 450:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="intro.html#cb90-1" tabindex="-1"></a><span class="dv">450</span></span></code></pre></div>
<pre><code>## [1] 450</code></pre>
</div>
<div id="writing-comments-in-r" class="section level2 hasAnchor" number="1.7">
<h2><span class="header-section-number">1.7</span> Writing Comments in R<a href="intro.html#writing-comments-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>The comment symbol in <strong>R</strong> is the <strong>hashmark</strong> symbol <code>#</code>.</p></li>
<li><p><span style="color:#D96716"><strong>Comments</strong></span> allow you to write notes in English (or any other human language) within your <strong>R</strong> programs.</p></li>
<li><p>Comments are basically pieces of text the computer <span style="color:#D96716"><strong>will ignore</strong></span> when
interpreting your code.</p></li>
<li><p>You can use comments to help <span style="color:#D96716"><strong>explain</strong></span> what your code is doing.</p></li>
<li><p>Writing comments becomes more helpful as your code becomes more complex.</p></li>
<li><p>Writing comments can make code more <span style="color:#D96716"><strong>readable</strong></span> for others.</p></li>
</ul>
<hr />
<ul>
<li><p>In <strong>R</strong>, the <span style="color:#D96716"><strong>hashmark symbol</strong></span> <code>#</code> marks the beginning of a comment.</p></li>
<li><p>Everything on a line <span style="color:#D96716"><strong>following</strong></span> the hashmark symbol is ignored.</p></li>
<li><p>In the following example, both the text “This is an example of a comment” and the assignment <code>x &lt;- 64</code> are ignored</p></li>
</ul>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="intro.html#cb92-1" tabindex="-1"></a><span class="co"># This is an example of a comment</span></span>
<span id="cb92-2"><a href="intro.html#cb92-2" tabindex="-1"></a></span>
<span id="cb92-3"><a href="intro.html#cb92-3" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">42</span></span>
<span id="cb92-4"><a href="intro.html#cb92-4" tabindex="-1"></a></span>
<span id="cb92-5"><a href="intro.html#cb92-5" tabindex="-1"></a><span class="co"># x &lt;- 64</span></span>
<span id="cb92-6"><a href="intro.html#cb92-6" tabindex="-1"></a></span>
<span id="cb92-7"><a href="intro.html#cb92-7" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 42</code></pre>
<ul>
<li><p>Note also that you can write comments on the <strong>same line</strong> as an R statement.</p>
<ul>
<li>Everything to the right of the hashmark <code>#</code> symbol will be ignored.</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="intro.html#cb94-1" tabindex="-1"></a><span class="co"># More </span></span>
<span id="cb94-2"><a href="intro.html#cb94-2" tabindex="-1"></a><span class="co"># examples </span></span>
<span id="cb94-3"><a href="intro.html#cb94-3" tabindex="-1"></a><span class="co"># of comments</span></span>
<span id="cb94-4"><a href="intro.html#cb94-4" tabindex="-1"></a></span>
<span id="cb94-5"><a href="intro.html#cb94-5" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">42</span>  <span class="do">## x &lt;- 24 </span></span>
<span id="cb94-6"><a href="intro.html#cb94-6" tabindex="-1"></a></span>
<span id="cb94-7"><a href="intro.html#cb94-7" tabindex="-1"></a><span class="co"># x &lt;- 64</span></span>
<span id="cb94-8"><a href="intro.html#cb94-8" tabindex="-1"></a></span>
<span id="cb94-9"><a href="intro.html#cb94-9" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 42</code></pre>
</div>
<div id="exercises" class="section level2 hasAnchor" number="1.8">
<h2><span class="header-section-number">1.8</span> Exercises<a href="intro.html#exercises" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li>Compute the number</li>
</ol>
<span class="math display">\[\begin{equation}
\frac{\sqrt{1.43 + 5^{1.2}}}{3}
\end{equation}\]</span>
<p>directly in the <strong>R</strong> console.</p>
<ol start="2" style="list-style-type: decimal">
<li>Write an <strong>R script</strong> that assigns the value …</li>
</ol>
<span class="math display">\[\begin{equation}
\ln\Big( 1 + \exp(-2^{1.4}) \Big) + \ln\Big(1 + 2\exp(3^{1.7}) \Big)
\end{equation}\]</span>
<p>to a variable named <code>x</code> and prints the result in the Console when you run
the script.</p>
<ol start="3" style="list-style-type: decimal">
<li>What will be the value of the variable <code>y</code> after running the following code?</li>
</ol>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="intro.html#cb96-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">2</span>)</span>
<span id="cb96-2"><a href="intro.html#cb96-2" tabindex="-1"></a>y <span class="ot">&lt;-</span> x[<span class="dv">2</span>] <span class="sc">+</span> <span class="fu">max</span>(x)<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li>Which of the following is <strong>NOT</strong> a valid variable name in <strong>R</strong>?
<ul>
<li>.independent_variable3</li>
<li>_independent_variable3</li>
<li>independent_variable3</li>
<li>independent.variable3</li>
</ul></li>
</ol>

</div>
</div>



            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ifelse.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/nchenderson/IntroductiontoR/edit/master/01-intro.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/nchenderson/IntroductiontoR/blob/master/01-intro.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
